#!/usr/bin/env python

import subprocess
import sys

packages_to_install = set(
    [
        "ollama",
    ]
)
packages_installed_str = subprocess.run(
    ["brew", "list"],
    capture_output=True,
    text=True,
).stdout.strip()
packages_installed = set(packages_installed_str.split())

for package in packages_installed - packages_to_install:
    subprocess.run(["brew", "uninstall", package])

for package in packages_to_install - packages_installed:
    subprocess.run(["brew", "install", package])