#!/usr/bin/env python

import subprocess
flatpaks_to_install = set(
    [
        "ai.jan.Jan",
        "com.bitwarden.desktop",
        "com.brave.Browser",
        "com.github.johnfactotum.Foliate",
        "com.github.neithern.g4music",
        "com.github.rafostar.Clapper",
        "com.github.tchx84.Flatseal",
        "com.ranfdev.DistroShelf",
        "com.valvesoftware.Steam",
        "com.valvesoftware.SteamLink",
        "io.missioncenter.MissionCenter",
        "me.kozec.syncthingtk",
        "net.opentabletdriver.OpenTabletDriver",
        "org.gnome.Loupe",
        "org.gnome.Papers",
        "org.gnome.TextEditor",
        "org.gtk.Gtk3theme.Adwaita-dark",
        "org.onlyoffice.desktopeditors",
        "sh.ppy.osu",
    ]
)
flatpaks_installed_str = subprocess.run(
    ["flatpak", "--user", "list", "--app", "--columns=application"],
    capture_output=True,
    text=True,
).stdout.strip()
flatpaks_installed = set(flatpaks_installed_str.split())

subprocess.run(["flatpak", "--user", "remote-add", "--if-not-exists", "flathub", "https://dl.flathub.org/repo/flathub.flatpakrepo"])
subprocess.run(["flatpak", "--user", "-y", "update"])

for flatpak in flatpaks_installed - flatpaks_to_install:
    subprocess.run(["flatpak", "--user", "-y", "uninstall", flatpak])

for flatpak in flatpaks_to_install - flatpaks_installed:
    subprocess.run(["flatpak", "--user", "-y", "install", "flathub", flatpak])

overrides = [
    ("com.valvesoftware.Steam", "--filesystem=/mnt/games"),
    ("com.brave.Browser", "--filesystem=home"),
]
for override_package, override_arg in overrides:
    print("Overriding", override_package, override_arg)
    subprocess.run(["flatpak", "override", "--user", override_package, override_arg])
