#!/usr/bin/env python

import subprocess
flatpaks_to_install = set(
    [
        "com.bitwarden.desktop",
        "com.brave.Browser",
        "com.github.neithern.g4music",
        "com.github.rafostar.Clapper",
        "com.github.tchx84.Flatseal",
        "com.valvesoftware.Steam",
        "dev.zed.Zed",
        "io.missioncenter.MissionCenter",
        "net.opentabletdriver.OpenTabletDriver",
        "org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/23.08",
        "org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/24.08",
        "org.gnome.Boxes",
        "org.gnome.Loupe",
        "org.gnome.Papers",
        "org.gnome.TextEditor",
        "org.godotengine.GodotSharp",
        "org.gtk.Gtk3theme.Adwaita-dark",
        "org.onlyoffice.desktopeditors",
        "sh.ppy.osu",
    ]
)
flatpaks_installed_str = subprocess.run(
    ["flatpak", "--user", "list", "--app", "--columns=application"],
    capture_output=True,
    text=True,
).stdout.strip()
flatpaks_installed = set(flatpaks_installed_str.split())

subprocess.run(["flatpak", "--user", "-y", "update"])

for flatpak in flatpaks_installed - flatpaks_to_install:
    subprocess.run(["flatpak", "--user", "-y", "uninstall", flatpak])

for flatpak in flatpaks_to_install - flatpaks_installed:
    subprocess.run(["flatpak", "--user", "-y", "install", flatpak])

overrides = [
    ("com.valvesoftware.Steam", "--filesystem=/mnt/games")
]
for override_package, override_arg in overrides:
    print("Overriding", override_package, override_arg)
    subprocess.run(["flatpak", "override", "--user", override_package, override_arg])
