#!/usr/bin/env python

import subprocess

to_reset = ["org.gnome.shell", "org.gnome.desktop.wm.keybindings"]

for reset_dir in to_reset:
    subprocess.run(["gsettings", "reset-recursively", reset_dir])

gsettings_keys = {
    "org.gnome.desktop.background.picture-uri": "file:///usr/share/backgrounds/fedora-workstation/mermaid_dark.webp",
    "org.gnome.desktop.background.picture-uri-dark": "file:///usr/share/backgrounds/fedora-workstation/mermaid_dark.webp",
    "org.gnome.desktop.interface.clock-format": "24h",
    "org.gnome.desktop.interface.color-scheme": "prefer-dark",
    "org.gnome.desktop.interface.cursor-theme": "Adwaita",
    "org.gnome.desktop.interface.gtk-theme": "Adwaita",
    "org.gnome.desktop.interface.icon-theme": "Adwaita",
    "org.gnome.shell.favorite-apps": "['org.gnome.Ptyxis.desktop', 'org.gnome.Nautilus.desktop', 'com.brave.Browser.desktop', 'com.vscodium.codium.desktop', 'dev.zed.Zed.desktop']",
}
gsettings_keys.update(
    {
        f"org.gnome.shell.keybindings.switch-to-application-{i}": "[]"
        for i in range(1, 9)
    }
)
gsettings_keys.update(
    {
        f"org.gnome.desktop.wm.keybindings.switch-to-workspace-{i}": f"['<Super>{i}']"
        for i in range(1, 9)
    }
)
gsettings_keys.update(
    {
        f"org.gnome.desktop.wm.keybindings.move-to-workspace-{i}": f"['<Super><Shift>{i}']"
        for i in range(1, 9)
    }
)

for key, value in gsettings_keys.items():
    cmd = ["gsettings", "set"] + key.rsplit(".", 1) + [value]
    subprocess.run(cmd)

subprocess.run(["xdg-settings", "set", "default-web-browser", "com.brave.Browser.desktop"])
