FROM mcr.microsoft.com/dotnet/sdk:9.0 AS base

RUN apt-get update && apt-get install -y unzip

# SSH Installation
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    openssh-server \
    sudo
RUN mkdir -p /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN rm -rf /var/lib/apt/lists/*
EXPOSE 22

# LSP
RUN mkdir -p /omnisharp \
    && curl -L -o omnisharp.zip "https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.13/omnisharp-linux-x64-net6.0.zip" \
    && unzip omnisharp.zip -d /omnisharp \
    && rm omnisharp.zip

WORKDIR /workspace

ENTRYPOINT [ "/bin/bash" ]
